language: python
sudo: false
cache: pip
python:
- '3.6'
env:
  matrix:
  - DJANGO=111
install:
- pip install --upgrade tox
before_script:
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- tox -e $TOXENV
deploy:
  provider: pypi
  user: luispiedra
  password:
    secure: cF314C0+PQslT9VzJn0+fI+Y+Y4Lx+TrOj39KJI//T5IefqcUHdhtr3k0SZkY6Evewve6jrmgO5GpbjQWM9s8+P5lnFRTF05iMiALamLLc6+Ae9p4jfaWF0uCWJpHTCJgNKG4y7er1dokwFFNhK4nxTwjTHniHLD5P8xXrxX9NS/h3kP2KJl9QHN4ZKoQK/X/40c8iZJV8hmHnktlqYXlLWrHgTBOwdSEc/aPitYkXems9bdxxlbgpmm2MIw9m7hHICgLIBxtuHUXlAt2LsfCEaV/zrecFOQsNCM83ABsGsQMCcNEGduR1PDKOA8fYomc3Kn2pKwSagudiIXW8Y+D0Of/yDQceNdxbeAq8Xh1B2y8ITCHYG99qfZLYs99SI3f3yiYZyCHRz3PQFfoCfos7SZbaGLGzCghQOY+gi9TfaNyH1ZZgPLP+F1MNGTLxaONxr931eOpRDLtlkPnaTjYKMu9iMdSidm+PQ0Y5Zs/uLs5VZDc93DNYm+rj3hseHtUqYDIE3nSx7Wsxy/PJY7J3gYFO84lCnQtnKKpPTTAPuZ+iwkvbkQSK1GhJrwbGmT5VqLpM2pCfgUuW15ro74eO2OmuayF9lwm/lZADzSAGHUsMuJsWxyF+ThKYAy6hK/CwjwxUp+ALucPXzCAC6rv9Ye+qrOx8kRlrJZ3wK848I=
  # on:
    # tags: true
    # distributions: sdist bdist_wheel
    # repo: emigue/django-health-check-plus
    # branch: master
after_deploy:
  - cat $HOME/.pypirc
