language: python
sudo: false
cache: pip
python:
- '3.6'
env:
  matrix:
  - DJANGO=111
  - DJANGO=22
  - DJANGO=32
install:
- pip install --upgrade tox
before_script:
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- tox -e $TOXENV
deploy:
  provider: pypi
  user: luispiedra
  password:
    secure: UncNq1MPs1C1hb7HiZI+A3zxUxR0/1eI9CCnrnkygMm6tv0I2DWQkssKTFGFlWF/snf75hB48cdCXntpKMLSyAPShGefCoYEgAdLgpoOl61u2Nu4HyZpHUVvi4D/UNKtschZUuT9Vq01+a2LYiRjhCEi7swcSQYIVqA1SpUSSGQr15/ItfqJtcAYVBBcCujEcNqst7wqlgrvNQh2N1hWx8fgwVRPHhiKRCLXHBtwvhhfaM3yaH1N/znRiI8+NV7IelMCLfYzwUqAF3pDdHSeBXznqKTJbDBusOOyzi5jd20Qf/AduuVHpBT0MZpH4VCWquu9NaHAQQYi3qaygAXQ0haIsl09/WtYVraWl4kJZnB1I5/KpXHRiFG1RZOi7A5XAa4REc924gSmgQyhpIpYboYDQdc6CZEJIsEUz9xrlJZ/0741BVyAhWcC+FjL7/bCXtU8PiCMB0/Bj0JEIYnjwozYEqHMpzdxhG08ug2GKN34vTh+XljfYG+IyZLX382JVc/2VVCxX+BauM6Pb5EhFWMJua/yIgXMDdt/brHqCAWyn7lDty3ODMaequ9IXKHMqnuw+FflIo/OTnhx5qea4js/6Eb4t+H07nqMnYzZ2uQqMaaqr0PvSLTE46z50BHrPPySYlsubsfvDhlImEMoJReu+GZsTibz/g/TrhIxsd4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: emigue/django-health-check-plus
    branch: master
